version: '3'
services:

  web:
    build: .
    restart: always
    depends_on:
      - "db"
      - "milvus"
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"

  milvus:
    image: milvusdb/milvus:0.8.0-cpu-d041520-464400
    restart: always
    volumes:
      - ${VECTORDB_WD}/milvus-conf:/var/lib/milvus/conf
    ports:
      - "19530:19530"
