version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ${VECTORDB_WD}/postgres/db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  milvus:
    image: milvusdb/milvus:0.6.0-cpu-d120719-2b40dd
    restart: always
    volumes:
      - ${VECTORDB_WD}/milvus-conf:/var/lib/milvus/conf
      - ${VECTORDB_WD}/milvus/db:/var/lib/milvus/db
      - ${VECTORDB_WD}/milvus/logs:/var/lib/milvus/logs
